"""Create and open one PDF generated by the training agent."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Callable

from services.pdf_service import PdfService
from tools.desktop.desktop_tools import OpenFileTool
from tools.tool_context import ToolContext


class CreateTrainingPdfUseCase:
    """Persist a training response as a non-overwriting PDF and open it."""

    def __init__(
        self,
        pdf_service: PdfService,
        open_file_tool: OpenFileTool,
        *,
        now_provider: Callable[[], datetime] = datetime.now,
    ) -> None:
        self._pdf_service = pdf_service
        self._open_file_tool = open_file_tool
        self._now_provider = now_provider

    def execute(self, content: str, output_dir: str | Path) -> str:
        if not isinstance(content, str):
            raise TypeError("content debe ser str.")
        if not content.strip():
            raise ValueError("No se puede crear un PDF vacio.")

        directory = Path(output_dir)
        directory.mkdir(parents=True, exist_ok=True)
        target = self._next_path(directory)
        self._pdf_service.create(content, target)

        try:
            self._open_file_tool.execute(ToolContext(parameters={"path": str(target)}))
        except Exception as error:
            raise RuntimeError(
                f"PDF creado en {target}, pero no se pudo abrir: {error}"
            ) from error

        return f"PDF creado y abierto: {target}"

    def _next_path(self, output_dir: Path) -> Path:
        timestamp = self._now_provider().strftime("%Y%m%d_%H%M%S")
        base = output_dir / f"entrenamiento_{timestamp}.pdf"
        if not base.exists():
            return base

        index = 1
        while True:
            candidate = output_dir / f"entrenamiento_{timestamp}_{index}.pdf"
            if not candidate.exists():
                return candidate
            index += 1
